# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e458d01dd187d4941bb99548a78e9421"
name = "MenuCraft"
application_url = "https://prefer-wrapped-hood-camel.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mega-menu-test-2.myshopify.com"
include_config_on_deploy = true

[app_proxy]
url = "https://toll-reaches-wellness-impressed.trycloudflare.com/proxy"
subpath = "menucraft"
prefix = "apps"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://prefer-wrapped-hood-camel.trycloudflare.com/auth/callback"
]
