import type { IconSource } from "@shopify/polaris";
import {
  BlogIcon,
  ChevronDownIcon,
  CodeIcon,
  CollectionIcon,
  CollectionListIcon,
  EmailIcon,
  HomeIcon,
  ImageIcon,
  LayoutBlockIcon,
  ListBulletedIcon,
  MenuIcon,
  PageIcon,
  ProductIcon,
  ProductListIcon,
  SearchIcon,
} from "@shopify/polaris-icons";
import type { BlockTemplateId, BuilderSettings, MenuItem, SubmenuTemplateId } from "./types";

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  { id: "home", label: "Home", url: "/", role: "menu" },
  {
    id: "catalogs",
    label: "Catalogs",
    url: "/collections",
    role: "menu",
    expanded: true,
    children: [
      {
        id: "catalogs-list-1",
        label: "Pet Food",
        url: "",
        role: "group",
        expanded: true,
        children: [
          { id: "pet-food", label: "Wet Foods", url: "/collections/wet-foods", role: "item" },
          { id: "dry-foods", label: "Dry Foods", url: "/collections/dry-foods", role: "item" },
          { id: "raw-foods", label: "Raw Foods", url: "/collections/raw-foods", role: "item" },
        ],
      },
      {
        id: "catalogs-list-2",
        label: "Pet Beds",
        url: "",
        role: "group",
        expanded: true,
        children: [
          { id: "pet-beds", label: "Bolster Beds", url: "/collections/bolster-beds", role: "item" },
          { id: "pillow-beds", label: "Pillow Beds", url: "/collections/pillow-beds", role: "item" },
          { id: "tent-beds", label: "Tent Beds", url: "/collections/tent-beds", role: "item" },
        ],
      },
      {
        id: "catalogs-list-3",
        label: "Pet Accessories",
        url: "",
        role: "group",
        expanded: true,
        children: [
          { id: "pet-blanket", label: "Pet Blanket", url: "/collections/pet-blanket", role: "item" },
          { id: "pet-belts", label: "Pet Belts", url: "/collections/pet-belts", role: "item" },
          { id: "pet-clothes", label: "Pet Clothes", url: "/collections/pet-clothes", role: "item" },
        ],
      },
      {
        id: "catalogs-list-4",
        label: "Pet Toys",
        url: "",
        role: "group",
        expanded: true,
        children: [
          { id: "stuffed-toys", label: "Stuffed Toys", url: "/collections/stuffed-toys", role: "item" },
          { id: "puzzle-toys", label: "Puzzle Toys", url: "/collections/puzzle-toys", role: "item" },
          { id: "rope-toys", label: "Rope Toys", url: "/collections/rope-toys", role: "item" },
        ],
      },
    ],
  },
  { id: "sale", label: "Sale", url: "/collections/sale", role: "menu" },
  { id: "blog", label: "Blog", url: "/blogs/news", role: "menu" },
  { id: "about", label: "About", url: "/pages/about", role: "menu" },
];

export const buildDefaultMenuItems = (): MenuItem[] => [
  structuredClone(DEFAULT_MENU_ITEMS[0]),
];

export const LINK_SUGGESTIONS = [
  { label: "Home", url: "/", icon: HomeIcon },
  { label: "Search", url: "/search", icon: SearchIcon },
  { label: "All collections", url: "/collections", icon: CollectionListIcon },
  { label: "All products", url: "/collections/all", icon: ProductListIcon },
  { label: "Collections", url: "/collections", icon: CollectionIcon },
  { label: "Products", url: "/products", icon: ProductIcon },
  { label: "Pages", url: "/pages", icon: PageIcon },
  { label: "Blogs", url: "/blogs", icon: BlogIcon },
  { label: "Blog posts", url: "/blogs/news", icon: BlogIcon },
];

export const SUBMENU_TEMPLATES: Array<{ id: SubmenuTemplateId; label: string; icon: IconSource }> = [
  { id: "custom", label: "Custom menu", icon: MenuIcon },
  { id: "tabs", label: "Tabs", icon: CollectionListIcon },
  { id: "mega", label: "Mega menu", icon: ProductListIcon },
  { id: "dropdown", label: "Dropdown (flyout)", icon: ChevronDownIcon },
];

export const BLOCK_TEMPLATES: Array<{ id: BlockTemplateId; label: string; icon: IconSource }> = [
  { id: "multi", label: "Multi block", icon: LayoutBlockIcon },
  { id: "tabs", label: "Tabs", icon: CollectionListIcon },
  { id: "image", label: "Image", icon: ImageIcon },
  { id: "links", label: "Link list", icon: ListBulletedIcon },
  { id: "product", label: "Product", icon: ProductIcon },
  { id: "collection", label: "Collection list", icon: CollectionIcon },
  { id: "blogs", label: "Blogs", icon: BlogIcon },
  { id: "contact", label: "Contact form", icon: EmailIcon },
  { id: "html", label: "Custom HTML", icon: CodeIcon },
];

export const DEFAULT_BUILDER_SETTINGS: BuilderSettings = {
  animationDesktopTrigger: "hover",
  animationMobileTrigger: "toggle",
  animationEffect: "fade",
  animationDuration: 300,
  animationDelay: 150,
  spacingMainPadding: 20,
  spacingMainRowHeight: 50,
  spacingDropdownRowHeight: 50,
  spacingTabRowHeight: 50,
  spacingLinkListRowHeight: 30,
  carouselAutoPlay: true,
  carouselLoop: true,
  advancedMobileBreakpoint: 768,
  advancedHideLinkListSubmenu: false,
  advancedShowAddToCart: false,
  advancedEnableLazyLoading: true,
  elementsShowSearch: true,
  elementsShowDesktopDivider: true,
  elementsShowMobileDivider: true,
  elementsShowIndicators: true,
  layoutLocation: "auto",
  layoutOrientation: "horizontal",
  layoutAlignment: "left",
  layoutMaxWidth: "1200px",
  accountShowLogin: true,
  accountShowRegister: true,
  accountShowAccount: true,
  accountShowLogout: true,
  accountLoginIcon: "",
  accountLoginLabel: "",
  accountLoginIconWidthMode: "auto",
  accountLoginIconWidthValue: 50,
  accountLoginIconWidthUnit: "%",
  accountRegisterIcon: "",
  accountRegisterLabel: "",
  accountRegisterIconWidthMode: "auto",
  accountRegisterIconWidthValue: 50,
  accountRegisterIconWidthUnit: "%",
  accountAccountIcon: "",
  accountAccountLabel: "",
  accountAccountIconWidthMode: "auto",
  accountAccountIconWidthValue: 50,
  accountAccountIconWidthUnit: "%",
  accountLogoutIcon: "",
  accountLogoutLabel: "",
  accountLogoutIconWidthMode: "auto",
  accountLogoutIconWidthValue: 50,
  accountLogoutIconWidthUnit: "%",
  submenuShowBorder: true,
  submenuEnableDesktopScroll: true,
  submenuEnableMobileScroll: true,
  submenuMaxWidth: "1200px",
  submenuMobileStyle: "drawer",
  typographyMainUseCustom: false,
  typographyMainFont: "Shopify Sans, Inter, system-ui, sans-serif",
  typographyMainWeight: 500,
  typographyMainSize: 15,
  typographySubheadingUseCustom: false,
  typographySubheadingFont: "Shopify Sans, Inter, system-ui, sans-serif",
  typographySubheadingWeight: 600,
  typographySubheadingSize: 15,
  typographySubtextUseCustom: false,
  typographySubtextFont: "Shopify Sans, Inter, system-ui, sans-serif",
  typographySubtextWeight: 400,
  typographySubtextSize: 13,
  typographyTabUseCustom: false,
  typographyTabFont: "Shopify Sans, Inter, system-ui, sans-serif",
  typographyTabWeight: 500,
  typographyTabSize: 14,
  colorMainBackground: "#0b0b0b",
  colorMainBackgroundHover: "#111111",
  colorMainDivider: "#1f1f1f",
  colorMainText: "#f5f5f5",
  colorMainTextHover: "#ffffff",
  colorTabHeading: "#111111",
  colorTabHeadingActive: "#111111",
  colorTabBackgroundActive: "#f5f5f5",
  colorSubmenuBackground: "#ffffff",
  colorSubmenuBorder: "#e5e7eb",
  colorSubmenuHeading: "#b91c1c",
  colorSubmenuText: "#111827",
  colorSubmenuTextHover: "#4D5BCD",
  colorSubmenuDescription: "#969696",
  colorSubmenuDescriptionHover: "#4D5BCD",
  colorBadgeSaleText: "#FFFFFF",
  colorBadgeSaleBackground: "#EC523E",
  colorBadgeSoldOutText: "#757575",
  colorBadgeSoldOutBackground: "#D5D5D5",
  colorButtonText: "#FFFFFF",
  colorButtonBackground: "#1F1F1F",
  colorButtonBackgroundHover: "#000000",
  colorButtonTextHover: "#FFFFFF",
  customCss: "",
  imageLibrary: [],
};

export const FONT_OPTIONS = [
  { label: "Work Sans", value: "Work Sans, system-ui, sans-serif" },
  { label: "Shopify Sans", value: "Shopify Sans, Inter, system-ui, sans-serif" },
  { label: "Inter", value: "Inter, system-ui, sans-serif" },
  { label: "Helvetica", value: "Helvetica, Arial, sans-serif" },
  { label: "Arial", value: "Arial, sans-serif" },
  { label: "Georgia", value: "Georgia, serif" },
  { label: "Times New Roman", value: "\"Times New Roman\", serif" },
  { label: "Roboto", value: "Roboto, system-ui, sans-serif" },
  { label: "Open Sans", value: "\"Open Sans\", system-ui, sans-serif" },
  { label: "Lato", value: "Lato, system-ui, sans-serif" },
  { label: "Montserrat", value: "Montserrat, system-ui, sans-serif" },
  { label: "Poppins", value: "Poppins, system-ui, sans-serif" },
  { label: "Nunito", value: "Nunito, system-ui, sans-serif" },
  { label: "Source Sans 3", value: "\"Source Sans 3\", system-ui, sans-serif" },
  { label: "Raleway", value: "Raleway, system-ui, sans-serif" },
  { label: "Merriweather", value: "Merriweather, serif" },
  { label: "Playfair Display", value: "\"Playfair Display\", serif" },
  { label: "PT Sans", value: "\"PT Sans\", system-ui, sans-serif" },
  { label: "Fira Sans", value: "Fira Sans, system-ui, sans-serif" },
  { label: "Noto Sans", value: "\"Noto Sans\", system-ui, sans-serif" },
  { label: "Noto Serif", value: "\"Noto Serif\", serif" },
  { label: "IBM Plex Sans", value: "\"IBM Plex Sans\", system-ui, sans-serif" },
  { label: "Ubuntu", value: "Ubuntu, system-ui, sans-serif" },
  { label: "Rubik", value: "Rubik, system-ui, sans-serif" },
  { label: "Cabin", value: "Cabin, system-ui, sans-serif" },
  { label: "Manrope", value: "Manrope, system-ui, sans-serif" },
  { label: "DM Sans", value: "\"DM Sans\", system-ui, sans-serif" },
  { label: "Space Grotesk", value: "\"Space Grotesk\", system-ui, sans-serif" },
  { label: "Quicksand", value: "Quicksand, system-ui, sans-serif" },
  { label: "Inconsolata", value: "Inconsolata, monospace" },
  { label: "JetBrains Mono", value: "\"JetBrains Mono\", monospace" },
];
