export const PREVIEW_IMAGE_SOURCES = [
  "/vertical-dropdown.png",
  "/horizantal-dropdown.png",
  "/simple-left-tabs.png",
  "/simple-right-tabs.png",
  "/simple-top-tabs.png",
  "/two-top-tabs.png",
  "/three-top-tabs.png",
  "/two-level-tabs.png",
  "/three-level-tabs.png",
  "/two-nested-tabs.png",
  "/three-nested-tabs.png",
  "/Space.png",
  "/4-product-list.png",
  "/link-list-multiblock.png",
  "/1link-list+3product-columns.png",
  "/3columns+1photo.png",
  "/product-carousel.png",
  "/2columns+2photos.png",
  "/1link-list+product-carousel.png",
  "/1column%20+%203photos.png",
  "/image+product-carousel.png",
  "/4images.png",
  "/4products.png",
  "/map-contact-adres.png",
  "/custom menu image.png",
  "/image%201.png",
  "/I%CC%87mage%202.png",
  "/two-columns.png",
  "/3-columns.png",
  "/easy-column.png",
  "/columns-with-icons.png",
  "/product-grid.png",
  "/product.png",
  "/product-yatay.png",
  "/product-list.png",
  "/product-grid-horizontal.png",
  "/collection-list.png",
  "/horizontal-collection-list.png",
  "/articles-blog.png",
  "/latest-blog.png",
  "/contact%20form.png",
  "/custom-html.png",
];

export const HOVER_PREVIEW_DELAY_MS = 0;
export const HOVER_PREVIEW_CLEAR_DELAY_MS = 150;
